services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ofitec
      POSTGRES_USER: ofitec
      POSTGRES_PASSWORD: ofitec
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build: ./backend
    env_file: .env
    depends_on: [db, redis]
    ports: ["5555:5555"]
    volumes: ["./backend:/app"]
    command: ["sh", "-c", "python app/wait_for_db.py && uvicorn app.main:app --host 0.0.0.0 --port 5555 --reload"]

  frontend:
    build: ./frontend
    env_file: .env
    depends_on: [backend]
    ports: ["3001:3000"]
    volumes: ["./frontend:/app", "/app/node_modules"]
    command: ["npm", "run", "dev"]

volumes:
  pgdata:
